name: Native image builds
concurrency:
  # Group PRs by head_ref, push to main branch by commit id, and others branch by ref.
  group: ${{ github.workflow }}-${{ github.head_ref || (github.ref == 'refs/heads/main' && github.sha) || github.ref }}
  cancel-in-progress: true
on: [push, pull_request]
env:
  JHI_SAMPLES: ${{ github.workspace }}/generator-jhipster-quarkus/test-integration/samples/
jobs:
  applications:
    name: ${{ matrix.app }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, '[ci skip]') && !contains(github.event.head_commit.message, '[skip ci]')"
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        node_version: [16.x]
        os: [ubuntu-latest]
        app:
          - imperative-ngx-jwt-maven-mysql-caffeine
          - imperative-ngx-jwt-maven-mongodb-caffeine
          - imperative-ngx-jwt-gradle-mongodb-redis
          - imperative-ngx-jwt-maven-psql-nocache
          - imperative-react-jwt-gradle-mysql-caffeine
          - imperative-ngx-jwt-maven-mysql-redis
          - imperative-sql-jwt-maven-no-db
          - imperative-ngx-oauth2-maven-mysql-caffeine
        include:
            - app: imperative-ngx-jwt-maven-mysql-caffeine
            - app: imperative-ngx-jwt-maven-mongodb-caffeine
            - app: imperative-ngx-jwt-maven-psql-nocache
            - app: imperative-react-jwt-gradle-mysql-caffeine
            - app: imperative-ngx-jwt-maven-mysql-redis
            - app: imperative-sql-jwt-maven-no-db
            - app: imperative-ngx-oauth2-maven-mysql-caffeine
        exclude:
            - app: imperative-ngx-jwt-gradle-mongodb-redis
    env:
      JHI_APP: ${{ matrix.app }}
    steps:
      - name: 'SETUP: Checkout quarkus blueprint'
        uses: actions/checkout@v3
        with:
          path: generator-jhipster-quarkus
          fetch-depth: 5
      - name: 'SETUP: Checkout generator-jhipster'
        uses: actions/checkout@v3
        with:
          repository: 'jhipster/generator-jhipster'
          ref: v7.9.3
          path: generator-jhipster
      - name: 'SETUP: environment'
        id: setup
        uses: ./generator-jhipster/.github/actions/setup
        with:
          jdl-sample: ${{ github.workspace }}/generator-jhipster-quarkus/test-integration/samples/${{ matrix.app }}.jdl
          generator-jhipster-branch: local
          jhipster-bom-branch: ignore
          package-with-executable: generator-jhipster-quarkus
          executable: jhipster-quarkus
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.setup.outputs.node-version }}
      - uses: graalvm/setup-graalvm@v1
        with:
           version: '22.3.0'
           java-version: '11'
           components: 'native-image'
           github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Generate: Project'
        uses: ./generator-jhipster/.github/actions/generate
      - name: 'MERGE: generate base'
        continue-on-error: true
        id: base-app
        if: github.event.pull_request
        uses: ./generator-jhipster/.github/actions/compare-base
      - name: 'MERGE: compare changes'
        continue-on-error: true
        id: compare
        if: steps.base-app.outcome == 'success'
        uses: ./generator-jhipster/.github/actions/compare
      - name: 'Run JHipster Quarkus Native'
        id: native
        run: ./generator-jhipster-quarkus/test-integration/scripts/03-run-server-native.sh $JHI_APP
      - name: 'Store failsafe-reports'
        uses: actions/upload-artifact@v2
        if: always() && steps.native.outcome == 'failure'
        with:
          name: failsafe-reports-${{ matrix.app }}
          path: /home/runner/app/target/failsafe-reports
